"""Generate docs/results.html and docs/api.html from the committed result files.

The published page has no numbers of its own: every table is rendered from
results/*.json, so the site cannot drift from what the code actually produced.
Run tools/figures.py first, then this script, then commit docs/ together with
results/.
"""
from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(ROOT, "results")
DOCS = os.path.join(ROOT, "docs")

HEADER = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>stochastic-latent-bounds</title>
  <meta name="description" content="Sound stochastic Lyapunov certificates for high-dimensional physical systems via invertible latent transports">
  <style>
    body { background-color:#fff; padding:50px; font:14px/1.5 "Noto Sans","Helvetica Neue",Helvetica,Arial,sans-serif; color:#727272; font-weight:400; }
    h1,h2,h3,h4,h5,h6 { color:#222; margin:0 0 20px; }
    p,ul,ol,table,pre,dl { margin:0 0 20px; }
    h1,h2,h3 { line-height:1.1; }
    h1 { font-size:28px; } h2 { color:#393939; } h3 { color:#494949; }
    a { color:#267CB9; text-decoration:none; }
    a:hover,a:focus { color:#069; font-weight:bold; }
    strong { color:#222; font-weight:700; }
    .wrapper { width:860px; margin:0 auto; }
    header { width:270px; float:left; position:fixed; -webkit-font-smoothing:subpixel-antialiased; }
    header h1 a { color:#222; }
    section { width:500px; float:right; padding-bottom:50px; }
    code,pre { font-family:Monaco,"Bitstream Vera Sans Mono","Lucida Console",Terminal,Consolas,"Liberation Mono","DejaVu Sans Mono",monospace; color:#333; }
    pre { padding:8px 15px; background:#f8f8f8; border-radius:5px; border:1px solid #e5e5e5; overflow-x:auto; }
    table { width:100%; border-collapse:collapse; }
    th,td { text-align:left; padding:5px 10px; border-bottom:1px solid #e5e5e5; }
    dt { color:#444; font-weight:700; }
    th { color:#444; }
    img { max-width:100%; }
    figcaption { font-size:11px; color:#777; margin-top:4px; }
    figure { margin:0 0 20px; }
    hr { border:0; background:#e5e5e5; height:1px; margin:0 0 20px; }
    footer { width:270px; float:left; position:fixed; bottom:50px; -webkit-font-smoothing:subpixel-antialiased; }
    .formula { font-family:Monaco,Consolas,"Liberation Mono",monospace; font-size:12.5px; background:#f8f8f8; border-left:3px solid #aa0000; padding:8px 12px; margin:0 0 20px; overflow-x:auto; }
    .stats { display:grid; grid-template-columns:repeat(auto-fit,minmax(88px,1fr)); gap:6px; margin:0 0 20px; }
    .stat { border:1px solid #e5e5e5; border-radius:5px; padding:6px 8px; }
    .stat .v { font-size:15px; color:#222; font-weight:700; }
    .stat .k { font-size:10px; color:#777; line-height:1.35; margin-top:2px; }
    .badges { color:#777; }
    .badges span { border:1px solid #e5e5e5; border-radius:999px; padding:1px 9px; margin-right:5px; font-size:11px; display:inline-block; }
    @media print, screen and (max-width: 960px) {
      div.wrapper { width:auto; margin:0; }
      header,section,footer { float:none; position:static; width:auto; }
      header { padding-right:320px; }
      section { border:1px solid #e5e5e5; border-width:1px 0; padding:20px 0; margin:0 0 20px; }
    }
    @media print, screen and (max-width: 720px) {
      body { word-wrap:break-word; padding:30px; } header { padding:0; }
    }
    @media print, screen and (max-width: 480px) { body { padding:15px; } }
  </style>
</head>
<body>
<div class="wrapper">
<header>
  <h1><a href="index.html">stochastic&#8209;latent&#8209;bounds</a></h1>
  <p>Sound stochastic Lyapunov certificates for high&#8209;dimensional physical systems, via invertible latent transports</p>
  <p class="view"><a href="https://github.com/sehajr-singhs/stochastic-latent-bounds">View My GitHub Profile</a></p>
  <strong><a href="index.html">Overview</a></strong><br>
  <strong><a href="results.html">Results</a></strong><br>
  &nbsp;&nbsp;&nbsp;<a href="results.html#tightness">Tightness (exp3)</a><br>
  &nbsp;&nbsp;&nbsp;<a href="results.html#scaling">Scaling (exp1)</a><br>
  &nbsp;&nbsp;&nbsp;<a href="results.html#hotswap">Hot&#8209;swap gate (exp2)</a><br>
  &nbsp;&nbsp;&nbsp;<a href="results.html#ladder">Effort ladder (exp1b)</a><br>
  &nbsp;&nbsp;&nbsp;<a href="results.html#cmapss">C&#8209;MAPSS fleet (exp4)</a><br>
  &nbsp;&nbsp;&nbsp;<a href="results.html#airquality">Air quality (exp5)</a><br>
  <strong><a href="math.html">Mathematics</a></strong><br>
  <strong><a href="api.html">API</a></strong><br>
</header>
"""

FOOTER = """
<footer>
  <p>Generated by <code>tools/site.py</code> from committed result files.<br>
  Regenerate: <code>python tools/figures.py &amp;&amp; python tools/site.py</code></p>
</footer>
</div>
</body>
</html>
"""


def _load(name):
    p = os.path.join(RESULTS, name)
    if not os.path.exists(p):
        return None
    with open(p, encoding="utf-8") as fh:
        return json.load(fh)


def _fmt(v, nd=3):
    if v is None:
        return "&mdash;"
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, float):
        return f"{v:.{nd}f}"
    return str(v)


def _table(headers, rows):
    o = ["<table>", "<tr>" + "".join(f"<th>{h}</th>" for h in headers) + "</tr>"]
    for r in rows:
        o.append("<tr>" + "".join(f"<td>{c}</td>" for c in r) + "</tr>")
    o.append("</table>")
    return "\n".join(o)


def _fig(name, caption):
    return (f'<figure><img src="assets/{name}" alt="{caption}">'
            f"<figcaption>{caption}</figcaption></figure>")


def build_results():
    o = [HEADER]
    o.append("<section>")
    o.append('<h2 id="tightness">1. Tightness of the Ito bound (exp3)</h2>')
    d3 = _load("exp3_tightness.json")
    if d3:
        beta, tol = d3["beta"], d3["tol"]
        o.append(
            f'<p>N-link arm (<code>n_links={d3["n_links"]}</code>, latent factor '
            f'<code>d={d3["d_eta"]}</code>). Noise floor <code>&beta; = {_fmt(beta, 5)}</code>, '
            f"tolerance <code>tol = {tol:g}</code>, so the certificate constant is "
            f"<code>&beta;+tol = {_fmt(beta + tol, 5)}</code> and the guaranteed noise-ball "
            f'radius is <code>(&beta;+tol)/&alpha; = {_fmt((beta + tol) / d3["alpha"], 4)}</code>.</p>')
        rows = []
        for r in d3["rows"]:
            rows.append([f"{r['width']:g}", _fmt(r["tight_upper"], 4), _fmt(r["cs_upper"], 4),
                         _fmt(r["tight_excess"], 4), _fmt(r["cs_excess"], 4),
                         "yes" if r["tight_certifies"] else "<b>no</b>",
                         "yes" if r["cs_certifies"] else "<b>no</b>"])
        o.append(_table(["box half&#8209;width w", "tight upper", "C-S upper",
                         "tight &minus; &beta;", "C-S &minus; &beta;",
                         "tight certifies (&le;&beta;+tol)", "C-S certifies (&le;&beta;+tol)"], rows))
        o.append(_fig("fig1_tightness.svg",
                      "Bound excess over the noise floor versus box half-width (log-log). "
                      "The Cauchy&#8209;Schwarz bound's excess is bounded away from zero; the tight "
                      "interval trace vanishes as the box shrinks."))
    else:
        o.append('<p class="muted">results/exp3_tightness.json not present.</p>')

    o.append('<h2 id="scaling">2. Certified volume vs dimension (exp1)</h2>')
    d1 = _load("exp1.json")
    if d1:
        rows = []
        for r in d1["rows"]:
            rows.append([
                r["D"], r["d_eta"], _fmt(r["beta"], 4),
                _fmt(r["factor"]["certified_fraction"]),
                _fmt(r["full"]["certified_fraction"]),
                f"{r['factor']['nodes']} / {r['full']['nodes']}",
                f"{r['factor']['seconds']:.0f} / {r['full']['seconds']:.0f}",
                _fmt(r["world_model"].get("rel_err_mean"), 4),
                _fmt(r.get("lam_Q"), 3),
                "yes" if r.get("rho_metric_ok") else "<b>no</b>",
            ])
        o.append(_table(
            ["D", "d (&eta;)", "&beta;", "factor cert. frac.", "full cert. frac.",
             "nodes fac/full", "seconds fac/full", "world&#8209;model rel. err",
             "&lambda;&#8342;", "metric ok"], rows))
        o.append(_fig("fig2_scaling.svg",
                      "Certified fraction of the region under the same node and time budget. "
                      "Factor mode searches only the d-dimensional &eta;-box; full mode searches "
                      "all D coordinates."))
        o.append(
            '<div class="formula">certificate: L W + &alpha; W &le; &beta; + tol &nbsp;(&alpha;='
            f'{d1.get("alpha")}, &kappa;={d1.get("kappa")}, &sigma;={d1.get("sigma")}, tol={d1["rows"][0]["tol"] if d1["rows"] else 0.05})</div>')
    else:
        o.append('<p class="muted">results/exp1.json not present.</p>')

    o.append('<h2 id="hotswap">3. Gated online hot&#8209;swap (exp2)</h2>')
    d2 = _load("exp2.json")
    if d2:
        rows = []
        for gate, g in d2["gates"].items():
            rows.append([gate, g["accepted"], g["rejected"], g["unsafe_swaps"],
                         _fmt(g["unsafe_swap_fraction"]), g["fallback_rounds"],
                         f"{g['seconds']:.0f}"])
        o.append(_table(["gate", "accepted", "rejected", "unsafe swaps",
                         "unsafe fraction", "fallback rounds", "seconds"], rows))
        o.append(_fig("fig3_shadow.svg",
                      "Probe violation fraction over the stream. The plant's damping halves "
                      "halfway through; the sound gate swaps only what the interval bound "
                      "certifies, the naive gate swaps everything."))
    else:
        o.append('<p class="muted">results/exp2.json not present.</p>')

    o.append('<h2 id="ladder">4. Effort ladder: budget needed to reach equal quality (exp1b)</h2>')
    db = _load("exp1_budget.json")
    if db:
        o.append(
            "<p>Node budget is doubled per rung and <em>both</em> modes re-certified at "
            "every rung, so the comparison stays equal-effort. The stop rule is factor "
            "mode reaching the target fraction (or the budget cap); the ladder itself is "
            "the claim: the effort factor mode needs is set by the latent dimension "
            "d, while full mode does not finish at any affordable budget once D grows.</p>")
        rows = []
        for r in db["rows"]:
            for lvl in r["ladder"]:
                rows.append([
                    f"{r['tag']} (D={r['D']}, d={r['d_eta']})",
                    str(lvl["budget"]),
                    _fmt(lvl["factor"]["certified_fraction"]),
                    _fmt(lvl["full"]["certified_fraction"]),
                ])
        o.append(_table(["arm", "node budget", "factor cert. frac.",
                         "full cert. frac."], rows))
    else:
        o.append('<p class="muted">results/exp1_budget.json not present.</p>')

    o.append('<h2 id="cmapss">5. Real fleet data: NASA C-MAPSS aging drift (exp4)</h2>')
    d4 = _load("exp4_realtrend.json")
    if d4:
        ident, era, c4 = d4["identification"], d4["era"], d4["cert"]
        o.append(
            f"<p>The plants are linear-Gaussian (Ornstein&#8209;Uhlenbeck) models "
            f"<em>identified from the NASA C-MAPSS FD001 fleet</em> ({d4['dataset'].split('(')[-1].rstrip(')')}): "
            f"{len(ident['sensors'])} variable sensor channels per engine cycle, healthy era = first half "
            f"of each engine's life, aged era = second half. The identified aging shift is real: "
            f"attractor moves {ident['attractor_shift']:.2f} sd, ||&Delta;A|| = {ident['dA_norm']:.2f}. "
            f"Transport + latent world model trained on the healthy identified plant "
            f"(world-model fit vs exact push-forward: {d4['world_model'].get('rel_err_mean', float('nan')):.2f}).</p>")
        o.append(_table(
            ["quantity", "value"],
            [["noise floor &beta; (identified diffusion)", f"{d4['beta']:.2e}"],
             ["factor cert. frac. (d=%d of D=%d)" % (d4["d_eta"], d4["D"]),
              _fmt(c4["factor"]["certified_fraction"])],
             ["full cert. frac. (all D)", _fmt(c4["full"]["certified_fraction"])],
             ["era probe: viol. frac. healthy", _fmt(era["healthy"]["viol_frac"])],
             ["era probe: viol. frac. aged", _fmt(era["aged"]["viol_frac"])],
             ["shadow gate: unsafe swaps (sound / naive)",
              f"{d4['shadow']['sound']['unsafe_swaps']} / {d4['shadow']['naive']['unsafe_swaps']}"]]))
        o.append(_fig("fig4_realtrend.svg",
                      "Certificate-violation fraction under each identified fleet era. "
                      "The aging drift moves the plant out of the certified envelope; "
                      "the gate exists to catch exactly this."))
    else:
        o.append('<p class="muted">results/exp4_realtrend.json not present.</p>')

    o.append('<h2 id="airquality">6. Real environmental data: Beijing air&#8209;quality drift (exp5)</h2>')
    d5 = _load("exp5_airquality.json")
    if d5:
        ident, era, c5 = d5["identification"], d5["era"], d5["cert"]
        o.append(
            f"<p>A second physical domain: an Ornstein&#8209;Uhlenbeck plant identified from "
            f"hourly multi&#8209;pollutant records at {d5['dataset'].split(', ')[-1].split(' (')[0]} "
            f"(Beijing PRSA; 10 channels, hourly 2013&ndash;2017). The drift event is the real "
            f"seasonal regime shift: heating season (Nov&#8209;Mar, municipal schedule) vs the rest "
            f"of the year. Identified shift: attractor moves {ident['attractor_shift']:.2f} sd, "
            f"||&Delta;A|| = {ident['dA_norm']:.2f}. Same pipeline as exp4, zero domain&#8209;specific code.</p>")
        o.append(_table(
            ["quantity", "value"],
            [["noise floor &beta; (identified diffusion)", f"{d5['beta']:.2e}"],
             ["factor cert. frac. (d=%d of D=%d)" % (d5["d_eta"], d5["D"]),
              _fmt(c5["factor"]["certified_fraction"])],
             ["full cert. frac. (all D)", _fmt(c5["full"]["certified_fraction"])],
             ["era probe: viol. frac. non&#8209;heating", _fmt(era["healthy"]["viol_frac"])],
             ["era probe: viol. frac. heating", _fmt(era["aged"]["viol_frac"])],
             ["shadow gate: unsafe swaps (sound / naive)",
              f"{d5['shadow']['sound']['unsafe_swaps']} / {d5['shadow']['naive']['unsafe_swaps']}"]]))
        o.append(_fig("fig5_airquality.svg",
                      "Certificate-violation fraction under the two seasonal regimes of the "
                      "identified air&#8209;quality plant. The heating&#8209;season shift is the drift "
                      "event the hot&#8209;swap gate is designed for."))
    else:
        o.append('<p class="muted">results/exp5_airquality.json not present.</p>')

    o.append("<h2>How to reproduce</h2>")
    o.append("""<ul>
<li><code>python experiments/exp1_main.py</code> &mdash; trains and certifies each arm size (checkpointed; re-runs skip finished stages).</li>
<li><code>python experiments/exp2_shadow.py</code> &mdash; reuses the <code>arm4_d2</code> checkpoint from exp1.</li>
<li><code>python experiments/exp1_budget.py</code> &mdash; equal-quality budget ladder over the exp1 checkpoints.</li>
<li><code>python experiments/exp4_realtrend.py</code> &mdash; real-data pipeline (expects <code>data/cmapss/CMaps/train_FD001.txt</code> from Kaggle <code>behrad3d/nasa-cmaps</code>).</li>
<li><code>python experiments/exp5_airquality.py</code> &mdash; second real domain (expects <code>data/aqi/PRSA_Data_*.csv</code> from Kaggle <code>sid321axn/beijing-multisite-airquality-data-set</code>).</li>
<li><code>python experiments/exp3_tightness.py</code> &mdash; tightness sweep.</li>
<li><code>python -m pytest tests/ -q</code> &mdash; soundness, tightness, invertibility, metric, push&#8209;forward tests.</li>
</ul>""")
    o.append("</section>")
    o.append(FOOTER)
    html = "\n".join(o)
    with open(os.path.join(DOCS, "results.html"), "w", encoding="utf-8") as fh:
        fh.write(html)
    print("wrote docs/results.html")


def build_math():
    """Render docs/math.md (authoritative markdown) into the shared site shell."""
    import markdown
    with open(os.path.join(DOCS, "math.md"), encoding="utf-8") as fh:
        body = markdown.markdown(fh.read(), extensions=["fenced_code", "tables"])
    o = [HEADER, "<section>", body, "</section>", FOOTER]
    with open(os.path.join(DOCS, "math.html"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(o))
    print("wrote docs/math.html")


def build_api():
    o = [HEADER]
    o.append("<section>")
    o.append('<h2 id="apimap">API map</h2>')
    o.append("""<table>
<tr><th>module</th><th>role</th></tr>
<tr><td><code>sbounds.systems</code></td><td>Analytic N-link arm under gravity&#8209;compensated PD with velocity&#8209;block process noise; exact Ito push&#8209;forward of the physical SDE (the ground truth used for scoring, never for certification).</td></tr>
<tr><td><code>sbounds.transport</code></td><td>Invertible affine&#8209;coupling transport <code>T</code> with <code>T(x*)=0</code>; sound interval enclosures of <code>T</code>, <code>T&#8315;&sup1;</code> and the interval Jacobian <code>J T</code>.</td></tr>
<tr><td><code>sbounds.models</code></td><td><code>LyapunovNet</code> (positive&#8209;definite by construction) and <code>LatentDynamics</code> with <code>F(0)=0</code> enforced structurally; Lyapunov metric for the &rho; block; spectral&#8209;norm projection.</td></tr>
<tr><td><code>sbounds.nets</code></td><td>Interval arithmetic, IBP and interval forward&#8209;mode AD (ternary jets) with outward rounding.</td></tr>
<tr><td><code>sbounds.bounds</code></td><td>Sound bounds on <code>L W + &alpha; W</code>: tight interval Ito trace <code>&frac12; tr(BB&#7481; Hess W)</code> and the C&#8209;S baseline; full&#8209;space and factorised certification modes.</td></tr>
<tr><td><code>sbounds.region</code></td><td>Region definitions, bound factories, and BnB entry points with the <code>&beta;+tol</code> threshold.</td></tr>
<tr><td><code>sbounds.bnb</code></td><td>Worst&#8209;first branch&#8209;and&#8209;bound with explicit node/time budgets; certified fraction is a one&#8209;sided lower bound.</td></tr>
<tr><td><code>sbounds.generator</code></td><td>Exact (autograd) latent generator and the noise floor <code>&beta; = L W(0)</code>; evaluation only.</td></tr>
<tr><td><code>sbounds.train</code></td><td>Data generation (Euler&#8209;Maruyama), joint transport+drift training, certificate training on exact&#8209;generator violations.</td></tr>
<tr><td><code>sbounds.cegis</code></td><td>Counterexample search that separates genuine violations from bound looseness; verifier&#8209;in&#8209;the&#8209;loop retraining against model or exact&#8209;plant oracle.</td></tr>
<tr><td><code>sbounds.shadow</code></td><td>Dual&#8209;buffer shadow networks with a certified acceptance gate; counts unsafe swaps against the exact plant generator.</td></tr>
</table>""")
    o.append("<h2>The certificate, precisely</h2>")
    o.append("""<div class="formula">dy = F(y) dt + B(y) dW,  B = J T(x) &Sigma;(x),  y = T(x)
W(y) = V(&eta;) + &kappa; &rho;&#7481; Q &rho;,  Q: A&#7523;&#7523;&#7481;Q + Q A&#7523;&#7523; = &minus;I
L W(y) = &nabla;W&#183;F(y) + &frac12; tr( B B&#7481; Hess W )
claim: sup&#7522;&#7480; (L W + &alpha; W) &le; &beta; + tol,  &beta; = L W(0)
=&gt;  E[W(t)] &le; e&#8315;&#8311;t W&#8320; + ((&beta;+tol)/&alpha;)(1 &minus; e&#8315;&#8311;t)</div>""")
    o.append("""<p class="muted">The interval trace is sound because every elementwise product of intervals contains the
true product and sums of intervals contain the true sum; it is tight because both properties become
equalities on degenerate (point) boxes, so the bound converges to the exact generator under
refinement. The Cauchy&#8209;Schwarz form <code>&frac12;||B||&#7523;&sup2;||Hess W||&#7523;</code> is also sound but its slack is
bounded away from zero near the origin, which is why it certifies nothing there.</p>
<p class="muted">The drift terms use <b>centered (mean&#8209;value) forms</b>: the residual is evaluated
exactly at the box center and the deviation is bounded by a Jacobian enclosure whose entries are
exact zeros (the factorised residual&#8217;s &eta;&#8209;rows do not read &rho;) or Lipschitz balls (spectral&#8209;norm
products, capped during training). The remainder is quadratic in box radius, so subdivision
converges; raw interval bound propagation is linear and certifies nothing at region scale.</p>""")
    o.append("</section>")
    o.append(FOOTER)
    with open(os.path.join(DOCS, "api.html"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(o))
    print("wrote docs/api.html")


if __name__ == "__main__":
    os.makedirs(DOCS, exist_ok=True)
    build_results()
    build_math()
    build_api()
