theme: jekyll-theme-minimal
title: stochastic-latent-bounds
description: Sound stochastic Lyapunov certificates for high-dimensional physical systems via invertible latent transports
logo: false
show_downloads: false
google_analytics: false
